# -*- coding: utf-8 -*-
"""Python_Boruta_Wrapper_V1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tk1UZRPVlH26l5QFfIXCSrSm_rjYAJLy

# **Install and Import Neccessary Packages**
"""

import pandas as pd
!pip install boruta
from boruta import BorutaPy
from sklearn.ensemble import RandomForestClassifier

#Load CSV File of Data into the Google Colab Environment
from google.colab import files
upload = files.upload()

"""# **Import Data**"""

#Load the dataset
df = pd.read_csv('sales.csv')

#Top 10 Rows of Data
df.head

"""# **Define Target Variable**"""

#Separate the target variable
target = df['revenue']
df = df.drop(columns=['revenue'])

"""# **Create Random Forest Model**"""

#Create a Random Forest classifier object
rf = RandomForestClassifier(n_jobs=-1, class_weight='balanced', max_depth=5)

"""# **Create and Fit Boruta Wrapper Selector**"""

#Create the Boruta feature selector object
boruta_selector = BorutaPy(rf, n_estimators='auto', verbose=2, random_state=1)

#Fit the Boruta selector to the dataset
boruta_selector.fit(df.values, target.values)

"""# **Final Feature Selection**"""

#Print the selected features
selected_features = df.columns[boruta_selector.support_].to_list()
print('Selected features:', selected_features)
